language: python

python:
  - "3.6"

env:
  - DJANGO_VERSION=2.2.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt

services:
  - redis-server

script:
  - coverage run --source='.' --omit=*/migrations/* manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)