# Generated by Django 2.2.2 on 2019-06-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('bio', models.TextField(blank=True, verbose_name='Lecturer bio')),
            ],
        ),
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lection title')),
                ('description', models.TextField(blank=True, verbose_name='Lection description')),
                ('date', models.DateTimeField(blank=True, verbose_name='Lection date')),
                ('homework', models.TextField(blank=True, verbose_name='Lection homework')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lections', to='courses.Lecturer', verbose_name='Lection speaker')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course title')),
                ('description', models.TextField(blank=True, verbose_name='Course description')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Course full price')),
                ('lecturers', models.ManyToManyField(related_name='courses', to='courses.Lecturer', verbose_name='Course lecturers')),
            ],
        ),
    ]
