# Generated by Django 2.2.2 on 2019-10-06 15:22

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Course title')),
                ('description', models.TextField(blank=True, verbose_name='Course description')),
                ('price', models.PositiveIntegerField(verbose_name='Course full price')),
            ],
            bases=(courses.models.MetaMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('photo', models.ImageField(blank=True, upload_to='persons', verbose_name='Lecturers photo')),
                ('bio', models.TextField(blank=True, verbose_name='Lecturer bio')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(courses.models.MetaMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lesson title')),
                ('description', models.TextField(blank=True, verbose_name='Lesson description')),
                ('date', models.DateTimeField(blank=True, verbose_name='Lesson date')),
                ('homework', models.TextField(blank=True, verbose_name='Lesson homework')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.Course', verbose_name='Course')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lections', to='courses.Lecturer', verbose_name='Lesson speaker')),
            ],
            bases=(courses.models.MetaMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/user/avatar', verbose_name='User avatar')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='User birthdate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_property', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(courses.models.MetaMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Score')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='courses.Lecturer', verbose_name='Lecturer')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='courses.Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(courses.models.MetaMixin, models.Model),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(related_name='courses', to='courses.Lecturer', verbose_name='Course lecturers'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Course students'),
        ),
    ]
