# Generated by Django 2.2.2 on 2019-06-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='persons', verbose_name='Lecturers photo'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last name'),
        ),
    ]
