# Generated by Django 2.2.2 on 2019-06-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190606_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lesson title')),
                ('description', models.TextField(blank=True, verbose_name='Lesson description')),
                ('date', models.DateTimeField(blank=True, verbose_name='Lesson date')),
                ('homework', models.TextField(blank=True, verbose_name='Lesson homework')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lections', to='courses.Lecturer', verbose_name='Lesson speaker')),
            ],
        ),
        migrations.DeleteModel(
            name='Lection',
        ),
    ]
